[book]
authors = ["The OurMachinery Team"]
language = "en"
multilingual = false
src = "src"
title = "The Machinery Tutorial Book"

[output.html]
git-repository-url = "https://github.com/OurMachinery/themachinery-books"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
marker = "* auto-gen TOC;\n{:toc}"

[preprocessor.tera]
command = "mdbook-tera --toml ./context.toml"

[output.linkcheck]
follow-web-links = true
exclude = [ 'https://ourmachinery\.com/apidoc/' ]


#[preprocessor.autolink]
#renderer = ["html"]
#folder = "../"
#books = ["the_machinery_book","tutorials"]
#command = "python ../autogenerete_doc_links.py"