[book]
authors = ["The OurMachinery Team"]
language = "en"
multilingual = false
src = "src"
title = "The Machinery Book"

[output.html]
git-repository-url = "https://github.com/OurMachinery/themachinery-books"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
marker = "* auto-gen TOC;\n{:toc}"

[preprocessor.tera]
command = "mdbook-tera  --toml  ../context.toml"

[output.linkcheck]
