[book]
authors = ["The OurMachinery Team"]
language = "en"
multilingual = false
src = "src"
title = "The Machinery Book"

[output.html]
git-repository-url = "https://github.com/OurMachinery/themachinery-books"
