name: build github page
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout website
        uses: actions/checkout@v2
        with:
          path: ./
      - name: Cache mdbook-tera
        id: cache-mdbook-tera
        uses: actions/cache@v2
        with:
          path: ./mdbook_tera
          key: ${{ runner.os }}-mdbook-tera
      - uses: actions-rs/cargo@v1
        if: steps.cache-mdbook-tera.outputs.cache-hit != 'true'
        with:
          command: install
          args: mdbook-tera --root ./mdbook_tera
      - name: add mdbook-tera to PATH
        run: |
          export PATH="${{github.workspace}}/mdbook_tera/bin:$PATH"
          chmod +x ./mdbook_tera/bin/mdbook-tera
      - name: Setup mdbook
        run: |
          mkdir tools
          cd tools
          wget https://github.com/rust-lang/mdBook/releases/download/v0.4.10/mdbook-v0.4.10-x86_64-unknown-linux-gnu.tar.gz -O archive.tar.gz
          tar -xf archive.tar.gz
          chmod +x mdbook
          wget https://github.com/badboy/mdbook-toc/releases/download/0.7.0/mdbook-toc-0.7.0-x86_64-unknown-linux-gnu.tar.gz -O mdbook-toc.tar.gz
          tar -xf  mdbook-toc.tar.gz
          chmod +x mdbook-toc
          cd ../
          mkdir public
          cp index.html public/index.html
      - name: Build introduction
        run: |
          export PATH="${{github.workspace}}/mdbook_tera/bin:$PATH"
          export PATH="${{github.workspace}}/tools/:$PATH"
          cd the_machinery_book
          mdbook build
          mv book ../public/the_machinery_book
      - name: Build introduction
        run: |
          export PATH="${{github.workspace}}/mdbook_tera/bin:$PATH"
          export PATH="${{github.workspace}}/tools/:$PATH"
          cd tutorials
          mdbook build
          mv book ../public/tutorials
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public