name: build github page
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout website
        uses: actions/checkout@v2
        with:
          path: ./
      - name: Setup mdbook
        run: cargo install mdbook
      - name: Build introduction
        run: |
          cd the_engine_introduction
           mdbook build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./the_engine_introduction/book
          destination_dir: the_machinery_book
      - name: Build introduction
        run: |
          cd the_engine_introduction
           mdbook build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./the_engine_introduction/book
          destination_dir: tutorials