name: build github page
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout website
        uses: actions/checkout@v2
        with:
          path: ./
      - name: Setup mdbook
        run: |
          mkdir tools
          cd tools
          wget https://github.com/rust-lang/mdBook/releases/download/v0.4.10/mdbook-v0.4.10-x86_64-unknown-linux-gnu.tar.gz -O archive.tar.gz
          tar -xf archive.tar.gz
          chmod +x mdbook
      - name: Build introduction
        run: |
          export PATH="${{github.workspace}}/tools/:$PATH"
          cd the_engine_introduction
           mdbook build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./the_engine_introduction/book
          destination_dir: the_machinery_book
      - name: Build introduction
        run: |
          export PATH="${{github.workspace}}/tools/:$PATH"
          cd the_engine_introduction
           mdbook build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./the_engine_introduction/book
          destination_dir: tutorials